# -*- coding: utf-8 -*-
"""MLZ_HW_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hTtMCakTD0zoadcpCacHaa-IaGShg-1_
"""

!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

np.__version__

df = pd.read_csv("data.csv")

df

df.info()

df.median()

df.shape

df['Make'].value_counts()

df.groupby('Make')['Model'].nunique()

df['Make'].value_counts()

df.columns[df.isnull().any()]

df.columns[df.isnull().any()].shape

df.fillna(df.median())

df.median()

first_value = df[w*]